<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

route::get('prepare',function(){
    DB::unprepared("

    INSERT INTO roles (id, name, guard_name, created_at, updated_at) VALUES
    (1, 'admin', 'web', NULL, NULL);

    INSERT INTO permissions (id, name, guard_name, created_at, updated_at) VALUES
    (1, 'access_users', 'web', NULL, NULL),
    (3, 'admin_posts', 'web', NULL, NULL),
    (4, 'admin_categories', 'web', NULL, NULL);

    
    INSERT INTO role_has_permissions (permission_id, role_id) VALUES
    (1, 1),
    (3, 1),
    (4, 1);

    INSERT INTO model_has_roles (role_id, model_type, model_id) VALUES
    (1, 'App\Models\User', 1);

    INSERT INTO `countries` (`id`, `code`, `extended_code`, `name`, `name_local`, `nationality`, `nationality_local`) VALUES
(1, 'AW', 'ABW', 'Aruba', 'أروبا', 'Aruban', 'أوروبهيني'),
(2, 'AF', 'AFG', 'Afghanistan', 'أفغانستان', 'Afghan', 'أفغانستاني'),
(3, 'AO', 'AGO', 'Angola', 'أنغولا', 'Angolan', 'أنقولي'),
(4, 'AI', 'AIA', 'Anguilla', 'أنغيلا', 'Anguillan', 'أنغويلي'),
(5, 'AL', 'ALB', 'Albania', 'ألبانيا', 'Albanian', 'ألباني'),
(6, 'AD', 'AND', 'Andorra', 'أندورا', 'Andorran', 'أندوري'),
(7, 'AN', 'ANT', 'Netherlands Antilles', 'الأنتيل الهولندية', 'Dutch Antilier', 'هولندي'),
(8, 'AE', 'ARE', 'United Arab Emirates', 'الإمارات العربية المتحدة', 'Emirati', 'إماراتي'),
(9, 'AR', 'ARG', 'Argentina', 'الأرجنتين', 'Argentinian', 'أرجنتيني'),
(10, 'AM', 'ARM', 'Armenia', 'أرمينيا', 'Armenian', 'أرميني'),
(11, 'AS', 'ASM', 'American Samoa', 'ساموا الأمريكية', 'American Samoan', 'أمريكي سامواني'),
(12, 'AQ', 'ATA', 'Antarctica', 'القارة القطبية الجنوبية', 'Antarctican', 'أنتاركتيكي'),
(13, 'TF', 'ATF', 'French Southern Territories', 'المقاطعات الجنوبية الفرنسية', 'French Southern Territories', 'المقاطعات الجنوبية الفرنسية'),
(14, 'AG', 'ATG', 'Antigua and Barbuda', 'أنتيغوا وباربودا', 'Antiguan', 'بربودي'),
(15, 'AU', 'AUS', 'Australia', 'أستراليا', 'Australian', 'أسترالي'),
(16, 'AT', 'AUT', 'Austria', 'النمسا', 'Austrian', 'نمساوي'),
(17, 'AZ', 'AZE', 'Azerbaijan', 'أذربيجان', 'Azerbaijani', 'أذربيجاني'),
(18, 'BI', 'BDI', 'Burundi', 'برونداي', 'Burundian', 'بورونيدي'),
(19, 'BE', 'BEL', 'Belgium', 'بلجيكا', 'Belgian', 'بلجيكي'),
(20, 'BJ', 'BEN', 'Benin', 'بنين', 'Beninese', 'بنيني'),
(21, 'BF', 'BFA', 'Burkina Faso', 'بوركينافاسو', 'Burkinabe', 'بوركيني'),
(22, 'BD', 'BGD', 'Bangladesh', 'بنغلاديش', 'Bangladeshi', 'بنغلاديشي'),
(23, 'BG', 'BGR', 'Bulgaria', 'بلغاريا', 'Bulgarian', 'بلغاري'),
(24, 'BH', 'BHR', 'Bahrain', 'البحرين', 'Bahraini', 'بحريني'),
(25, 'BS', 'BHS', 'Bahamas', 'باهاماس', 'Bahamian', 'باهاميسي'),
(26, 'BA', 'BIH', 'Bosnia and Herzegovina', 'البوسنة و الهرسك', 'Bosnian / Herzegovinian', 'بوسني/هرسكي'),
(27, 'BY', 'BLR', 'Belarus', 'بيلاروسيا', 'Belarusian', 'روسي'),
(28, 'BZ', 'BLZ', 'Belize', 'بليزي', 'Belizean', 'بيليزي'),
(29, 'BM', 'BMU', 'Bermuda', 'برمودا', 'Bermudan', 'برمودي'),
(30, 'BO', 'BOL', 'Bolivia', 'بوليفيا', 'Bolivian', 'بوليفي'),
(31, 'BR', 'BRA', 'Brazil', 'البرازيل', 'Brazilian', 'برازيلي'),
(32, 'BB', 'BRB', 'Barbados', 'باربادوس', 'Barbadian', 'بربادوسي'),
(33, 'BN', 'BRN', 'Brunei', 'بروناي', 'Bruneian', 'بروناي'),
(34, 'BT', 'BTN', 'Bhutan', 'بوتان', 'Bhutanese', 'بوتاني'),
(35, 'BV', 'BVT', 'Bouvet Island', 'جزيرة بوفيه', 'Bouvetian', 'بوفيهي'),
(36, 'BW', 'BWA', 'Botswana', 'بوتسوانا', 'Botswanan', 'بوتسواني'),
(37, 'CF', 'CAF', 'Central African Republic', 'إفريقيا الوسطى', 'Central African', 'أفريقي'),
(38, 'CA', 'CAN', 'Canada', 'كندا', 'Canadian', 'كندي'),
(39, 'CC', 'CCK', 'Cocos (Keeling) Islands', 'جزر كوكوس (كيلينغ)', 'Cocos Islander', 'جزر كوكوس'),
(40, 'CH', 'CHE', 'Switzerland', 'سويسرا', 'Swiss', 'سويسري'),
(41, 'CL', 'CHL', 'Chile', 'شيلي', 'Chilean', 'شيلي'),
(42, 'CN', 'CHN', 'China', 'الصين', 'Chinese', 'صيني'),
(43, 'CI', 'CIV', 'Côte d’Ivoire', 'الساحل العاج', 'Ivory Coastian', 'ساحل العاج'),
(44, 'CM', 'CMR', 'Cameroon', 'الكاميرون', 'Cameroonian', 'كاميروني'),
(45, 'CD', 'COD', 'Congo, The Democratic Republic of the', 'ج. الكونغو الديمقراطية (زائير سابقا)', 'Congolese', 'كونغو'),
(46, 'CG', 'COG', 'Congo', 'جمهورية الكونغو', 'Congolese', 'كونغي'),
(47, 'CK', 'COK', 'Cook Islands', 'جزر كوك', 'Cook Islander', 'جزر كوك'),
(48, 'CO', 'COL', 'Colombia', 'كولومبيا', 'Colombian', 'كولومبي'),
(49, 'KM', 'COM', 'Comoros', 'كوموروس', 'Comorian', 'جزر القمر'),
(50, 'CV', 'CPV', 'Cape Verde', 'الرأس الأخضر', 'Cape Verdean', 'الرأس الأخضر'),
(51, 'CR', 'CRI', 'Costa Rica', 'كوستا ريكا', 'Costa Rican', 'كوستاريكي'),
(52, 'CU', 'CUB', 'Cuba', 'كوبا', 'Cuban', 'كوبي'),
(53, 'CX', 'CXR', 'Christmas Island', 'جزيرة الكريسماس', 'Christmas Islander', 'جزيرة عيد الميلاد'),
(54, 'KY', 'CYM', 'Cayman Islands', 'جزر كايمان', 'Caymanian', 'كايماني'),
(55, 'CY', 'CYP', 'Cyprus', 'قبرص', 'Cypriot', 'قبرصي'),
(56, 'CZ', 'CZE', 'Czech Republic', 'التشيك', 'Czech', 'تشيكي'),
(57, 'DE', 'DEU', 'Germany', 'ألمانيا', 'German', 'ألماني'),
(58, 'DJ', 'DJI', 'Djibouti', 'دجيبوتي', 'Djiboutian', 'جيبوتي'),
(59, 'DM', 'DMA', 'Dominica', 'الدومينكان', 'Dominican', 'دومينيكي'),
(60, 'DK', 'DNK', 'Denmark', 'الدانمارك', 'Danish', 'دنماركي'),
(61, 'DO', 'DOM', 'Dominican Republic', 'جمهورية الدومينكان', 'Dominican', 'دومينيكي'),
(62, 'DZ', 'DZA', 'Algeria', 'الجزائر', 'Algerian', 'جزائري'),
(63, 'EC', 'ECU', 'Ecuador', 'الإكوادور', 'Ecuadorian', 'إكوادوري'),
(64, 'EG', 'EGY', 'Egypt', 'مصر', 'Egyptian', 'مصري'),
(65, 'ER', 'ERI', 'Eritrea', 'إيريتيريا', 'Eritrean', 'إريتيري'),
(66, 'EH', 'ESH', 'Western Sahara', 'الصحراء الغربية', 'Sahrawian', 'صحراوي'),
(67, 'ES', 'ESP', 'Spain', 'إسبانيا', 'Spanish', 'إسباني'),
(68, 'EE', 'EST', 'Estonia', 'إستونيا', 'Estonian', 'استوني'),
(69, 'ET', 'ETH', 'Ethiopia', 'إثيوبيا', 'Ethiopian', 'أثيوبي'),
(70, 'FI', 'FIN', 'Finland', 'فنلندا', 'Finnish', 'فنلندي'),
(71, 'FJ', 'FJI', 'Fiji Islands', 'فيجي', 'Fijian', 'فيجي'),
(72, 'FK', 'FLK', 'Falkland Islands', 'جزر فلكلاند', 'Falkland Islander', 'فوكلاندي'),
(73, 'FR', 'FRA', 'France', 'فرنسا', 'French', 'فرنسي'),
(74, 'FO', 'FRO', 'Faroe Islands', 'جزر فارو', 'Faroese', 'جزر فارو'),
(76, 'GA', 'GAB', 'Gabon', 'الغابون', 'Gabonese', 'غابوني'),
(77, 'GB', 'GBR', 'United Kingdom', 'إنجلترا', 'British', 'بريطاني'),
(78, 'GE', 'GEO', 'Georgia', 'جورجيا', 'Georgian', 'جيورجي'),
(79, 'GH', 'GHA', 'Ghana', 'غانا', 'Ghanaian', 'غاني'),
(80, 'GI', 'GIB', 'Gibraltar', 'جبل طارق', 'Gibraltar', 'جبل طارق'),
(81, 'GN', 'GIN', 'Guinea', 'غينيا', 'Guinean', 'غيني'),
(82, 'GP', 'GLP', 'Guadeloupe', 'جوادلوب', 'Guadeloupe', 'جزر جوادلوب'),
(83, 'GM', 'GMB', 'Gambia', 'غامبيا', 'Gambian', 'غامبي'),
(84, 'GW', 'GNB', 'Guinea-Bissau', 'غينيا بيساو', 'Guinea-Bissauan', 'غيني'),
(85, 'GQ', 'GNQ', 'Equatorial Guinea', 'غينيا الإستوائية', 'Equatorial Guinean', 'غيني'),
(86, 'GR', 'GRC', 'Greece', 'اليونان', 'Greek', 'يوناني'),
(87, 'GD', 'GRD', 'Grenada', 'غرندا', 'Grenadian', 'غرينادي'),
(88, 'GL', 'GRL', 'Greenland', 'جرينلاند', 'Greenlandic', 'جرينلاندي'),
(89, 'GT', 'GTM', 'Guatemala', 'غواتيمالا', 'Guatemalan', 'غواتيمالي'),
(90, 'GF', 'GUF', 'French Guiana', 'غويانا الفرنسية', 'French Guianese', 'غويانا الفرنسية'),
(91, 'GU', 'GUM', 'Guam', 'غوام', 'Guamanian', 'جوامي'),
(92, 'GY', 'GUY', 'Guyana', 'غويانا', 'Guyanese', 'غياني'),
(93, 'HK', 'HKG', 'Hong Kong', 'هونج كونج', 'Hongkongese', 'هونغ كونغي'),
(94, 'HM', 'HMD', 'Heard Island and McDonald Islands', 'جزيرة هيرد وجزر ماكدونالد', 'Heard and Mc Donald Islanders', 'جزيرة هيرد وجزر ماكدونالد'),
(95, 'HN', 'HND', 'Honduras', 'هندوراس', 'Honduran', 'هندوراسي'),
(96, 'HR', 'HRV', 'Croatia', 'كرواتيا', 'Croatian', 'كوراتي'),
(97, 'HT', 'HTI', 'Haiti', 'هايتي', 'Haitian', 'هايتي'),
(98, 'HU', 'HUN', 'Hungary', 'هنغاريا', 'Hungarian', 'مجري'),
(99, 'ID', 'IDN', 'Indonesia', 'إندونيسيا', 'Indonesian', 'أندونيسيي'),
(100, 'IN', 'IND', 'India', 'الهند', 'Indian', 'هندي'),
(101, 'IO', 'IOT', 'British Indian Ocean Territory', 'إقليم المحيط الهندي البريطاني', 'British Indian Ocean Territory', 'إقليم المحيط الهندي البريطاني'),
(102, 'IE', 'IRL', 'Ireland', 'إيرلندا', 'Irish', 'إيرلندي'),
(103, 'IR', 'IRN', 'Iran', 'إيران', 'Iranian', 'إيراني'),
(104, 'IQ', 'IRQ', 'Iraq', 'العراق', 'Iraqi', 'عراقي'),
(105, 'IS', 'ISL', 'Iceland', 'إيسلندا', 'Icelandic', 'آيسلندي'),
(106, 'IL', 'ISR', 'Israel', 'إسرائيل', 'Israeli', 'إسرائيلي'),
(107, 'IT', 'ITA', 'Italy', 'إيطاليا', 'Italian', 'إيطالي'),
(108, 'JM', 'JAM', 'Jamaica', 'جمايكا', 'Jamaican', 'جمايكي'),
(109, 'JO', 'JOR', 'Jordan', 'الأردن', 'Jordanian', 'أردني'),
(110, 'JP', 'JPN', 'Japan', 'اليابان', 'Japanese', 'ياباني'),
(111, 'KZ', 'KAZ', 'Kazakhstan', 'كازخستان', 'Kazakh', 'كزخ'),
(112, 'KE', 'KEN', 'Kenya', 'كينيا', 'Kenyan', 'كيني'),
(113, 'KG', 'KGZ', 'Kyrgyzstan', 'قرغيزستان', 'Kyrgyzstani', 'قيرغيزستاني'),
(114, 'KH', 'KHM', 'Cambodia', 'كمبوديا', 'Cambodian', 'كمبودي'),
(115, 'KI', 'KIR', 'Kiribati', 'كيريباس', 'I-Kiribati', 'كيريباتي'),
(116, 'KN', 'KNA', 'Saint Kitts and Nevis', 'سانت كيتس ونيفيس', 'Kittitian/Nevisian', 'سانت كيتس ونيفس'),
(117, 'KR', 'KOR', 'South Korea', 'كوريا الجنوبية', 'South Korean', 'كوري'),
(118, 'KW', 'KWT', 'Kuwait', 'الكويت', 'Kuwaiti', 'كويتي'),
(119, 'LA', 'LAO', 'Laos', 'لاوس', 'Laotian', 'لاوسي'),
(120, 'LB', 'LBN', 'Lebanon', 'لبنان', 'Lebanese', 'لبناني'),
(121, 'LR', 'LBR', 'Liberia', 'ليبريا', 'Liberian', 'ليبيري'),
(122, 'LY', 'LBY', 'Libyan Arab Jamahiriya', 'ليبيا', 'Libyan', 'ليبي'),
(123, 'LC', 'LCA', 'Saint Lucia', 'سانت لوسيا', 'Saint Lucia', 'سانت لوسيا'),
(124, 'LI', 'LIE', 'Liechtenstein', 'ليختنشتاين', 'Liechtenstein', 'ليختنشتيني'),
(125, 'LK', 'LKA', 'Sri Lanka', 'سريلنكا', 'Sri Lankian', 'سريلانكي'),
(126, 'LS', 'LSO', 'Lesotho', 'ليسوتو', 'Basotho', 'ليوسيتي'),
(127, 'LT', 'LTU', 'Lithuania', 'لتوانيا', 'Lithuanian', 'لتوانيي'),
(128, 'LU', 'LUX', 'Luxembourg', 'لكسمبورغ', 'Luxembourger', 'لوكسمبورغي'),
(129, 'LV', 'LVA', 'Latvia', 'لاتفيا', 'Latvian', 'لاتيفي'),
(130, 'MO', 'MAC', 'Macao', 'ماكاو', 'Macanese', 'ماكاوي'),
(131, 'MA', 'MAR', 'Morocco', 'المغرب', 'Moroccan', 'مغربي'),
(132, 'MC', 'MCO', 'Monaco', 'موناكو', 'Monacan', 'مونيكي'),
(133, 'MD', 'MDA', 'Moldova', 'مولدوفا', 'Moldovan', 'مولديفي'),
(134, 'MG', 'MDG', 'Madagascar', 'مدغشقر', 'Malagasy', 'مدغشقري'),
(135, 'MV', 'MDV', 'Maldives', 'جزر المالديف', 'Maldivian', 'مالديفي'),
(136, 'MX', 'MEX', 'Mexico', 'المكسيك', 'Mexican', 'مكسيكي'),
(137, 'MH', 'MHL', 'Marshall Islands', 'جزر مارشال', 'Marshallese', 'مارشالي'),
(138, 'MK', 'MKD', 'Macedonia', 'مقدونيا', 'Macedonian', 'مقدوني'),
(139, 'ML', 'MLI', 'Mali', 'مالي', 'Malian', 'مالي'),
(140, 'MT', 'MLT', 'Malta', 'مالطا', 'Maltese', 'مالطي'),
(141, 'MM', 'MMR', 'Myanmar', 'ميانمار', 'Myanmarian', 'ميانماري'),
(142, 'MN', 'MNG', 'Mongolia', 'منغوليا', 'Mongolian', 'منغولي'),
(143, 'MP', 'MNP', 'Northern Mariana Islands', 'جزر ماريانا الشمالية', 'Northern Marianan', 'ماريني'),
(144, 'MZ', 'MOZ', 'Mozambique', 'موزمبيق', 'Mozambican', 'موزمبيقي'),
(145, 'MR', 'MRT', 'Mauritania', 'موريطانيا', 'Mauritanian', 'موريتانيي'),
(146, 'MS', 'MSR', 'Montserrat', 'مونتسرات', 'Montserratian', 'مونتسيراتي'),
(147, 'MQ', 'MTQ', 'Martinique', 'مارتينيك', 'Martiniquais', 'مارتينيكي'),
(148, 'MU', 'MUS', 'Mauritius', 'موريشيوس', 'Mauritian', 'موريشيوسي'),
(149, 'MW', 'MWI', 'Malawi', 'ملاوي', 'Malawian', 'مالاوي'),
(150, 'MY', 'MYS', 'Malaysia', 'ماليزيا', 'Malaysian', 'ماليزي'),
(151, 'YT', 'MYT', 'Mayotte', 'مايوت', 'Mahoran', 'مايوتي'),
(152, 'NA', 'NAM', 'Namibia', 'ناميبيا', 'Namibian', 'ناميبي'),
(153, 'NC', 'NCL', 'New Caledonia', 'كاليدونيا الجديدة', 'New Caledonian', 'كاليدوني'),
(154, 'NE', 'NER', 'Niger', 'النيجر', 'Nigerien', 'نيجيري'),
(155, 'NF', 'NFK', 'Norfolk Island', 'جزيرة نورفولك', 'Norfolk Islander', 'نورفوليكي'),
(156, 'NG', 'NGA', 'Nigeria', 'نيجريا', 'Nigerian', 'نيجيري'),
(157, 'NI', 'NIC', 'Nicaragua', 'نيكاراغوا', 'Nicaraguan', 'نيكاراجوي'),
(158, 'NU', 'NIU', 'Niue', 'نييوي', 'Niuean', 'ني'),
(159, 'NL', 'NLD', 'Netherlands', 'هولندا', 'Dutch', 'هولندي'),
(160, 'NO', 'NOR', 'Norway', 'النرويج', 'Norwegian', 'نرويجي'),
(161, 'NP', 'NPL', 'Nepal', 'نيبال', 'Nepalese', 'نيبالي'),
(162, 'NR', 'NRU', 'Nauru', 'ناورو', 'Nauruan', 'نوري'),
(163, 'NZ', 'NZL', 'New Zealand', 'نيوزيلندا', 'New Zealander', 'نيوزيلندي'),
(164, 'OM', 'OMN', 'Oman', 'عمان', 'Omani', 'عماني'),
(165, 'PK', 'PAK', 'Pakistan', 'باكستان', 'Pakistani', 'باكستاني'),
(166, 'PA', 'PAN', 'Panama', 'بناما', 'Panamanian', 'بنمي'),
(167, 'PN', 'PCN', 'Pitcairn', 'بيتكيرن', 'Pitcairn Islander', 'بيتكيرني'),
(168, 'PE', 'PER', 'Peru', 'بيرو', 'Peruvian', 'بيري'),
(169, 'PH', 'PHL', 'Philippines', 'الفلبين', 'Filipino', 'فلبيني'),
(170, 'PW', 'PLW', 'Palau', 'بالاو', 'Palauan', 'بالاوي'),
(171, 'PG', 'PNG', 'Papua New Guinea', 'بابوا غينيا الجديدة', 'Papua New Guinean', 'بابوي'),
(172, 'PL', 'POL', 'Poland', 'بولندا', 'Polish', 'بوليني'),
(173, 'PR', 'PRI', 'Puerto Rico', 'بورتوريكو', 'Puerto Rican', 'بورتي'),
(174, 'KP', 'PRK', 'North Korea', 'كوريا الشمالية', 'North Korean', 'كوري'),
(175, 'PT', 'PRT', 'Portugal', 'البرتغال', 'Portuguese', 'برتغالي'),
(176, 'PY', 'PRY', 'Paraguay', 'بارجواي', 'Paraguayan', 'بارغاوي'),
(177, 'PS', 'PSE', 'Palestine', 'فلسطين', 'Palestinian', 'فلسطيني'),
(178, 'PF', 'PYF', 'French Polynesia', 'بولينزيا الفرنسية', 'French Polynesian', 'بولينيزيي'),
(179, 'QA', 'QAT', 'Qatar', 'قطر', 'Qatari', 'قطري'),
(180, 'RE', 'REU', 'Réunion', 'ريونيون', 'Reunionese', 'ريونيوني'),
(181, 'RO', 'ROM', 'Romania', 'رومانيا', 'Romanian', 'روماني'),
(182, 'RU', 'RUS', 'Russian Federation', 'روسيا', 'Russian', 'روسي'),
(183, 'RW', 'RWA', 'Rwanda', 'رواندا', 'Rwandan', 'رواندا'),
(184, 'SA', 'SAU', 'Saudi Arabia', 'المملكة العربية السعودية', 'Saudi Arabian', 'سعودي'),
(185, 'SD', 'SDN', 'Sudan', 'السودان', 'Sudanese', 'سوداني'),
(186, 'SN', 'SEN', 'Senegal', 'السنغال', 'Senegalese', 'سنغالي'),
(187, 'SG', 'SGP', 'Singapore', 'سنغافورة', 'Singaporean', 'سنغافوري'),
(188, 'GS', 'SGS', 'South Georgia and the South Sandwich Islands', 'جورجيا الجنوبية وجزر ساندويتش الجنوبية', 'South Georgia', 'جورجيا الجنوبية'),
(189, 'SH', 'SHN', 'Saint Helena', 'سانت هيلينا', 'St. Helenian', 'هيلاني'),
(190, 'SJ', 'SJM', 'Svalbard and Jan Mayen', 'سفالبارد وجان مايان', 'Svalbardian/Jan Mayenian', 'سفالبارد ويان ماين'),
(191, 'SB', 'SLB', 'Solomon Islands', 'جزر سليمان', 'Solomon Island', 'جزر سليمان'),
(192, 'SL', 'SLE', 'Sierra Leone', 'سيراليون', 'Sierra Leonean', 'سيراليوني'),
(193, 'SV', 'SLV', 'El Salvador', 'السلفادور', 'Salvadoran', 'سلفادوري'),
(194, 'SM', 'SMR', 'San Marino', 'سان مارينو', 'Sammarinese', 'ماريني'),
(195, 'SO', 'SOM', 'Somalia', 'الصومال', 'Somali', 'صومالي'),
(196, 'PM', 'SPM', 'Saint Pierre and Miquelon', 'سان بيار وميكلون', 'St. Pierre and Miquelon', 'سان بيير وميكلوني'),
(197, 'ST', 'STP', 'Sao Tome and Principe', 'ساو تومي وبرينسيبي', 'Sao Tomean', 'ساو تومي وبرينسيبي'),
(198, 'SR', 'SUR', 'Suriname', 'سورينام', 'Surinamese', 'سورينامي'),
(199, 'SK', 'SVK', 'Slovakia', 'سلوفاكيا', 'Slovak', 'سولفاكي'),
(200, 'SI', 'SVN', 'Slovenia', 'سلوفينيا', 'Slovenian', 'سولفيني'),
(201, 'SE', 'SWE', 'Sweden', 'السويد', 'Swedish', 'سويدي'),
(202, 'SZ', 'SWZ', 'Swaziland', 'سوازيلندا', 'Swazi', 'سوازيلندي'),
(203, 'SC', 'SYC', 'Seychelles', 'سيشيل', 'Seychellois', 'سيشيلي'),
(204, 'SY', 'SYR', 'Syria', 'سوريا', 'Syrian', 'سوري'),
(205, 'TC', 'TCA', 'Turks and Caicos Islands', 'جزر تركس وكايكوس', 'Turks and Caicos Islands', 'جزر توركس وكايكوس'),
(206, 'TD', 'TCD', 'Chad', 'تشاد', 'Chadian', 'تشادي'),
(207, 'TG', 'TGO', 'Togo', 'توغو', 'Togolese', 'توغي'),
(208, 'TH', 'THA', 'Thailand', 'تايلاند', 'Thai', 'تايلندي'),
(209, 'TJ', 'TJK', 'Tajikistan', 'طاجيكستان', 'Tajikistani', 'طاجيكستاني'),
(210, 'TK', 'TKL', 'Tokelau', 'توكلو', 'Tokelaian', 'توكيلاوي'),
(211, 'TM', 'TKM', 'Turkmenistan', 'تركمستان', 'Turkmen', 'تركمانستاني'),
(212, 'TP', 'TMP', 'East Timor', 'تيمور الشرقية', 'East Timor', 'تيمور الشرقية'),
(213, 'TO', 'TON', 'Tonga', 'تونجا', 'Tongan', 'تونغي'),
(214, 'TT', 'TTO', 'Trinidad and Tobago', 'ترينيداد وتوباغو', 'Trinidadian/Tobagonian', 'ترينيداد وتوباغو'),
(215, 'TN', 'TUN', 'Tunisia', 'تونس', 'Tunisian', 'تونسي'),
(216, 'TR', 'TUR', 'Turkey', 'تركيا', 'Turkish', 'تركي'),
(217, 'TV', 'TUV', 'Tuvalu', 'توفالو', 'Tuvaluan', 'توفالي'),
(218, 'TW', 'TWN', 'Taiwan', 'تايوان', 'Taiwanese', 'تايواني'),
(219, 'TZ', 'TZA', 'Tanzania', 'تنزانيا', 'Tanzanian', 'تنزانيي'),
(220, 'UG', 'UGA', 'Uganda', 'أوغندا', 'Ugandan', 'أوغندي'),
(221, 'UA', 'UKR', 'Ukraine', 'أوكرانيا', 'Ukrainian', 'أوكراني'),
(222, 'UM', 'UMI', 'United States Minor Outlying Islands', 'الولايات المتحدة البعيدة الجزر الصغيرة', 'United States Minor Outlying Islands', 'الولايات المتحدة البعيدة الجزر الصغيرة'),
(223, 'UY', 'URY', 'Uruguay', 'أوروغواي', 'Uruguayan', 'أورغواي'),
(224, 'US', 'USA', 'United States', 'الولايات المتحدة', 'American', 'أمريكي'),
(225, 'UZ', 'UZB', 'Uzbekistan', 'أوزباكستان', 'Uzbek', 'أوزباكستاني'),
(226, 'VA', 'VAT', 'Holy See (Vatican City State)', 'الكرسي الرسولي', 'Holy See', 'الكرسي الرسولي'),
(227, 'VC', 'VCT', 'Saint Vincent and the Grenadines', 'سانت فنسينت والجرينادينز', 'Saint Vincent and the Grenadines', 'سانت فنسنت وجزر غرينادين'),
(228, 'VE', 'VEN', 'Venezuela', 'فنزويلا', 'Venezuelan', 'فنزويلي'),
(229, 'VG', 'VGB', 'Virgin Islands, British', 'الجزر العذراء البريطانية', 'Virgin Islands, British', 'الجزر العذراء البريطانية'),
(230, 'VI', 'VIR', 'Virgin Islands, U.S.', 'الجزر العذراء الأمريكية', 'Virgin Islands, U.S.', 'الجزر العذراء الأمريكية'),
(231, 'VN', 'VNM', 'Vietnam', 'الفيتنام', 'Vietnamese', 'فيتنامي'),
(232, 'VU', 'VUT', 'Vanuatu', 'فانواتو', 'Vanuatuan', 'فانواتي'),
(233, 'WF', 'WLF', 'Wallis and Futuna', 'والس وفوتونا', 'Wallis and Futuna', 'والس وفوتونا'),
(234, 'WS', 'WSM', 'Samoa', 'ساموا', 'Samoan', 'ساموي'),
(235, 'YE', 'YEM', 'Yemen', 'اليمن', 'Yemeni', 'يمني'),
(236, 'YU', 'YUG', 'Yugoslavia', 'يوغوسلافيا', 'Yugoslav', 'يوغسلاف'),
(237, 'ZA', 'ZAF', 'South Africa', 'جنوب إفريقيا', 'South African', 'أفريقي'),
(238, 'ZM', 'ZMB', 'Zambia', 'زامبيا', 'Zambian', 'زامبياني'),
(239, 'ZW', 'ZWE', 'Zimbabwe', 'زمبابوي', 'Zimbabwean', 'زمبابوي'),
(240, 'AX', 'ALA', 'Aland Islands', 'جزر آلاند', 'Aland Islander', 'آلاندي'),
(241, 'BL', 'BLM', 'Saint Barthelemy', 'سان بارتيلمي', 'Saint Barthelmian', 'سان بارتيلمي'),
(244, 'GG', 'GGY', 'Guernsey', 'غيرنزي', 'Guernsian', 'غيرنزي'),
(245, 'IM', 'IMN', 'Isle of Man', 'جزيرة مان', 'Manx', 'ماني'),
(246, 'JE', 'JEY', 'Jersey', 'جيرزي', 'Jersian', 'جيرزي'),
(248, 'XK', 'XK', 'Kosovo', 'كوسوفو', 'Kosovar', 'كوسيفي'),
(249, 'FM', 'FSM', 'Micronesia', 'مايكرونيزيا', 'Micronesian', 'مايكرونيزيي'),
(250, 'ME', 'MNE', 'Montenegro', 'الجبل الأسود', 'Montenegrin', 'الجبل الأسود'),
(251, 'MF', 'MAF', 'Saint Martin (French)', 'ساينت مارتن فرنسي', 'Saint Martin (French)', 'ساينت مارتن فرنسي'),
(252, 'SX', 'SX', 'Saint Martin (Dutch)', 'ساينت مارتن هولندي', 'Saint Martin (Dutch)', 'ساينت مارتن هولندي'),
(253, 'SS', 'SSD', 'South Sudan', 'جنوب السودان', 'South Sudanese', 'جنوب سوداني');
ALTER TABLE `countries`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `code_index` (`code`);

    


    ");
    return 'success';
});
